# Generated by Django 4.2 on 2024-09-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_programmer_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='age',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nickname',
            new_name='nacionalidad',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='fullname',
            new_name='nombre',
        ),
    ]
